config/routes.rb
Gallery::Application.routes.draw do
  resources :photo_galleries do
    resources :photos, :only => [:index]
  end
  resources :photos, :except => [:index]
  root to: "static_pages#root"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :title, :photo_img

  validates_presence_of :title, :photo_gallery, :photo_img
  validates_length_of :title, :maximum => 75
  validates_length_of :description, :maximum => 400

  belongs_to :photo_gallery,
  			:inverse_of => :photos

  has_attached_file :photo_img, :styles => {
  	:default_url => "https://s3-us-west-1.amazonaws.com/gallery-development/End-of-Watch+blinkbox.jpg",
  	:big => "500x500>",
  	:medium => "300x300>",
  	:small => "150x150>"
  }

end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base
  attr_accessible :description, :title, :gallery_img

  validates_presence_of :title
  validates_length_of :title, :maximum => 75
  validates_length_of :description, :maximum => 400

  has_many :photos,
  		:inverse_of => :photo_gallery

  has_attached_file :gallery_img, :styles => {
  	:default_url => "https://s3-us-west-1.amazonaws.com/gallery-development/End-of-Watch+blinkbox.jpg",
  	:big => "500x500>",
  	:medium => "300x300>",
  	:small => "150x150>"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController
	def index
		@galleries = PhotoGallery.all
		render :json => @galleries
	end

	def show
		@gallery = PhotoGallery.find(params[:id])
		reder :json => @gallery
	end

	def new
		render :new
	end

	def create
		@gallery = PhotoGallery.new(params[:photo_gallery])

		if @gallery.save
			redirect_to photo_galleries_url
		else
			redirect_to new_photo_gallery_url
		end
	end

	def edit

	end

	def update

	end

	def destroy

	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.where(:photo_gallery_id => params[:photo_gallery_id])
		render :json => @photos
	end

	def show
		@photo = Photo.find(params[:id])
		render :json => @photo
	end

	def new
		@galleries = PhotoGallery.all
		render :new
	end

	def create
		@parent_gallery = PhotoGallery.find(params[:photo_gallery_id])
		photo_titles, photo_descrips = params[:photo].values
		photo_data_sets = photo_titles.zip(photo_descrips)
		photo_data_sets.each do |title, description|
			@parent_gallery.photos.new(title: title, description: description)
		end

		if @parent_gallerys.save
			render :json => @parent_gallery
		else
			render :json => @parent_gallery.errors.full_messages.to_json
		end
	end

	def edit

	end

	def update

	end

	def destroy

	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root
		render :root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photo_galleries/index.html.haml
%h1 Photo Galleries

app/views/photo_galleries/new.html.haml
%h1 New Photo Gallery

%form{:action => "#{photo_galleries_url}", :method => "POST"}
	%input{:type => "hidden", :name => "authenticity_token", :value => "#{form_authenticity_token}"}
	
	%label{:for => "gallery-title"}
		Title
		%br
		%input#gallery-title{:type => "text", :name => "photo_gallery[title]"}
	%br	
	%label{:for => "gallery-description"}
		Description
		%br
		%input#gallery-description{:type => "text", :name => "photo_gallery[description]"}
	%br
	%input{:type => "submit"}

app/views/photos/new.html.haml
%h1 New Photo

%form{:action => "#{photos_url}", :method => "POST"}
	%input{:type=>"hidden", :name => "authenticity_token", :value => "form_autheticity_token"}
	
	%label{:for => "photo-title"}
		Title
		%br
		%input#photo-title{:type => "text", :name => "photo[title]"}
	
	%br
	
	%label{:for => "photo-description"}
		Description
		%br
		%input#photo-description{:type => "text", :name => "photo[description]"}

	%br

	%label{:for => "photo-gallery"}
		Gallery
		%br
		%select#photo-gallery{:name => "photo[photo_gallery_id]"}
			%option
			- @galleries.each do |gallery|
				%option{:value => "#{gallery.id}"}= gallery.title

		%br

	%input{:type => "submit"}

app/views/static_pages/root.html.haml
%script{:type => "text/javascript"}
	$(document).ready(function(){
	var $contentContainer = $("#content");
	Gallery.initialize({ $rootEl: $contentContainer });
	});	

%h1 Root Static Page

#content